blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<int:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<int:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(),name="add"),
    path('change/', views.PostChangeLV.as_view(),name="change"),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV
from bookmark.views import BookmarkLV, BookmarkDV
from phone.views import PhoneLV, PhoneDV
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(),name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('phone/', include('phone.urls')),
    path('namecard/', include('namecard.urls')),
    path('student/', include('student.urls')),
    path('', HomeView.as_view(), name='home'),
    path('photo/', include('photo.urls')),
    path('gwamok/', include('gwamok.urls')),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

namecard/urls.py
from django.urls import path
from namecard.views import NamecardLV, NamecardDV
from namecard import views

app_name = 'namecard'
urlpatterns = [
    path('', NamecardLV.as_view(), name='index'),
    path('<int:pk>/', NamecardDV.as_view(), name='namecard_detail'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.NamecardCreateView.as_view(),name="add"),
    path('change/', views.NamecardChangeLV.as_view(),name="change"),
    path('<int:pk>/update/', views.NamecardUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.NamecardDeleteView.as_view(), name="delete"),
]

namecard/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Namecard(models.Model):
    name = models.CharField('NAME', max_length=100, blank=False)
    tel = models.CharField('MOBILE', max_length=50, blank=False)
    company = models.CharField('COMPANY', max_length=50, blank=True)
    email = models.EmailField('EMAIL', max_length=50, blank=True)
    group = models.CharField('GROUP', max_length=50, blank=True)
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    birth_dt = models.DateTimeField('BIRTH DATE', auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('namecard:namecard_detail', args=(self.id,))

    class Meta:
        ordering = ('group', 'name',)

namecard/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# Create your views here.
from django.views.generic import FormView
from namecard.form import NamecardSearchForm
from django.db.models import Q
from django.shortcuts import render
from namecard.models import Namecard
from django.views.generic import CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

from namecard.models import Namecard


class NamecardLV(ListView):
    model = Namecard


class NamecardDV(DetailView):
    model = Namecard

class SearchFormView(FormView):
    form_class = NamecardSearchForm
    template_name = 'namecard/namecard_search.html'

    def form_valid(self, form):
        searchWord=form.cleaned_data['search_word']
        namecard_list= Namecard.objects.filter(Q(name__icontains=searchWord)|Q(tel__icontains=searchWord)|Q(email__icontains=searchWord)|Q(company__icontains=searchWord)|Q(group__icontains=searchWord)).distinct()

        context={}
        context['form']=form
        context['search_word']=searchWord
        context['object_list']=namecard_list

        return render(self.request, self.template_name,context)

class NamecardCreateView(LoginRequiredMixin, CreateView):
        model = Namecard
        fields = ['name', 'tel', 'company', 'email']
        success_url = reverse_lazy('namecard:index')

        def form_valid(self, form):
            form.instance.owner = self.request.user
            return super().form_valid(form)


class NamecardChangeLV(LoginRequiredMixin, ListView):
    template_name = 'namecard/namecard_change_list.html'

    def get_queryset(self):
        return Namecard.objects.filter(owner=self.request.user)


class NamecardUpdateView(OwnerOnlyMixin, UpdateView):
    model = Namecard
    fields = ['name', 'tel', 'company', 'email']
    success_url = reverse_lazy('namecard:index')


class NamecardDeleteView(OwnerOnlyMixin, DeleteView):
    model = Namecard
    success_url = reverse_lazy('namecard:index')

namecard/templates/namecard/namecard_change_list.html
{% extends "base.html" %}
{% block title %}namecard_change_list.html{% endblock %}
{% block content %}

<h1>Namecard Change-{{user}}</h1>
<br>

<table class="table table-bordered table-condensed table-striped">

    <thead>
    <tr class="table-primary">
        <th>Name</th>
        <th>Tel</th>
        <th>Company</th>
        <th>Email</th>
        <th>Owner</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    {% for item in object_list %}
    <tr>
        <td>{{item.name}}</td>
        <td>{{item.tel}}</td>
        <td>{{item.company}}</td>
        <td>{{item.email}}</td>
        <td>{{item.owner}}</td>
        <td><a href="{% url 'namecard:update' item.id %}">Update</a> </td>
        <td><a href="{% url 'namecard:delete' item.id %}">Delete</a> </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

namecard/templates/namecard/namecard_confirm_delete.html
{% extends "base.html" %}
{% block title %}namecard_confirm_delete.html{% endblock %}
{% block content %}

<h1>Namecard Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
</form>
{% endblock %}

namecard/templates/namecard/namecard_detail.html
{% extends "base.html" %}
{% block title %}namecard_detail.html{% endblock %}
{% block content %}

    <h1>{{object.name}}</h1>
   <div>
       <span>이름 : {{object.name}}, </span>
       <span>전화번호 : {{object.tel}}</span>
   </div>
<div>
    <span>이메일 : {{object.email}}, </span>
    <span>회사 : {{object.company}}</span>
</div>
<div>
    <span>그룹 : {{object.group}}</span>
</div>

{% endblock %}

namecard/templates/namecard/namecard_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}namecard_form.html{% endblock %}
{% block content %}

<h1>Namecard Create/Update-{{user}}</h1>
<p class="font-italic">This is a creation or update form for your namecard.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) belows</div>
    {{form.errors}}
</div>
{% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
    {{ form.name|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
      <div class="col-sm-5">
          {{ form.name|add_class:"form-control"|attr:"autofocus"}}
      </div>
    </div>
    <div class="form-group row">
    {{ form.tel|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
      <div class="col-sm-5">
          {{ form.tel|add_class:"form-control"|attr:"autofocus"}}
      </div>
    </div>
    <div class="form-group row">
    {{ form.company|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
      <div class="col-sm-5">
          {{ form.company|add_class:"form-control"}}
      </div>
    </div>
    <div class="form-group row">
    {{ form.email|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
      <div class="col-sm-5">
          {{ form.email|add_class:"form-control"}}
      </div>
    </div>

    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
             <input type="submit" value="Submit" class="btn btn-info">
        </div>
    </div>

</form>
{% endblock %}

namecard/templates/namecard/namecard_list.html
{% extends "base.html" %}
{% block title %}namecard_list.html{% endblock %}
{% block content %}

    <h1>Namecard List</h1>
    <ul>
        {% for namecard in object_list %}
        <li><a href="{% url 'namecard:namecard_detail' namecard.id %}">{{namecard}}</a> </li>
        {% endfor %}
    </ul>


{% endblock %}

namecard/templates/namecard/namecard_search.html
{% extends "base.html" %}
{% block title %}namecard_search.html{% endblock %}
{%block content %}
<h1>Namecard Search</h1>
<br>
<form action="." method="post">{% csrf_token %}
     {{form.as_table}}
     <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>
<br/><br/>
{% if object_list %}
   {% for namecard in object_list %}
    <h2><a href="{{namecard.get_absolute_url}}">{{namecard.name}}</a> </h2>
    {% endfor %}
  {% elif search_term %}
  <b><i>Search Word({{search_term}})Not Found!</i></b>
  {% endif %}
{% endblock %}